import type { WorkflowDefinition } from "@alhusseiniya/types/workflow";

export const invoiceApprovalDefinition: WorkflowDefinition = {
  id: "00000000-0000-0000-0000-000000000001",
  tenantId: 0,
  code: "invoice-approval",
  name: "Invoice Approval Workflow",
  nameAr: "سير عمل اعتماد الفواتير",
  description: "3-step approval: Submitter → Manager → Finance",
  entityType: "sales_invoice",
  version: 1,
  isActive: true,
  steps: [
    {
      id: "00000000-0000-0000-0000-000000000101",
      code: "submit",
      name: "Submit for Approval",
      nameAr: "تقديم للموافقة",
      type: "task",
      assigneeType: "creator",
      slaHours: 24,
      conditions: [],
      actions: [],
      transitions: [
        {
          toStepId: "00000000-0000-0000-0000-000000000102",
          type: "submit",
          condition: "",
          requiredRoles: [],
        },
      ],
      order: 1,
    },
    {
      id: "00000000-0000-0000-0000-000000000102",
      code: "manager_approve",
      name: "Manager Approval",
      nameAr: "موافقة المدير",
      type: "approval",
      assigneeType: "role",
      roleCode: "manager",
      slaHours: 48,
      conditions: [],
      actions: [],
      transitions: [
        {
          toStepId: "00000000-0000-0000-0000-000000000103",
          type: "approve",
          condition: "",
          requiredRoles: ["manager"],
        },
        {
          toStepId: "00000000-0000-0000-0000-000000000101",
          type: "reject",
          condition: "",
          requiredRoles: ["manager"],
        },
      ],
      order: 2,
    },
    {
      id: "00000000-0000-0000-0000-000000000103",
      code: "finance_approve",
      name: "Finance Approval",
      nameAr: "موافقة المالية",
      type: "approval",
      assigneeType: "role",
      roleCode: "accountant",
      slaHours: 24,
      conditions: [],
      actions: [],
      transitions: [],
      order: 3,
    },
  ],
  settings: {
    allowParallelExecution: false,
    allowReassignment: true,
    allowDelegation: true,
    escalationEnabled: true,
    escalationHours: 72,
    escalationToRole: "admin",
    autoCompleteOnFinalApproval: true,
    requireAllApprovals: true,
    allowCommentOnReject: true,
    requireCommentOnReject: true,
  },
  metadata: {},
  createdAt: new Date().toISOString(),
  createdBy: "system",
  updatedAt: new Date().toISOString(),
  updatedBy: "system",
};
