import type { WorkflowDefinition } from "@alhusseiniya/types/workflow";

export const voucherApprovalDefinition: WorkflowDefinition = {
  id: "00000000-0000-0000-0000-000000000002",
  tenantId: 0,
  code: "voucher-approval",
  name: "Voucher Approval Workflow",
  nameAr: "سير عمل اعتماد السندات",
  description: "Submit → Accountant Review → Manager Approve",
  entityType: "voucher",
  version: 1,
  isActive: true,
  steps: [
    {
      id: "00000000-0000-0000-0000-000000000201",
      code: "submit",
      name: "Submit Voucher",
      nameAr: "تقديم السند",
      type: "task",
      assigneeType: "creator",
      slaHours: 24,
      conditions: [],
      actions: [],
      transitions: [
        {
          toStepId: "00000000-0000-0000-0000-000000000202",
          type: "submit",
          condition: "",
          requiredRoles: [],
        },
      ],
      order: 1,
    },
    {
      id: "00000000-0000-0000-0000-000000000202",
      code: "accountant_review",
      name: "Accountant Review",
      nameAr: "مراجعة المحاسب",
      type: "approval",
      assigneeType: "role",
      roleCode: "accountant",
      slaHours: 48,
      conditions: [],
      actions: [],
      transitions: [
        {
          toStepId: "00000000-0000-0000-0000-000000000203",
          type: "approve",
          condition: "",
          requiredRoles: ["accountant"],
        },
        {
          toStepId: "00000000-0000-0000-0000-000000000201",
          type: "reject",
          condition: "",
          requiredRoles: ["accountant"],
        },
      ],
      order: 2,
    },
    {
      id: "00000000-0000-0000-0000-000000000203",
      code: "manager_approve",
      name: "Manager Approval",
      nameAr: "موافقة المدير",
      type: "approval",
      assigneeType: "role",
      roleCode: "manager",
      slaHours: 24,
      conditions: [],
      actions: [],
      transitions: [],
      order: 3,
    },
  ],
  settings: {
    allowParallelExecution: false,
    allowReassignment: true,
    allowDelegation: true,
    escalationEnabled: true,
    escalationHours: 72,
    escalationToRole: "admin",
    autoCompleteOnFinalApproval: true,
    requireAllApprovals: true,
    allowCommentOnReject: true,
    requireCommentOnReject: true,
  },
  metadata: {},
  createdAt: new Date().toISOString(),
  createdBy: "system",
  updatedAt: new Date().toISOString(),
  updatedBy: "system",
};
